### ISSUE TITLE
c4 does not support "int* - int*" operation

### ISSUE THREAD

**Issue by pclouds** [rswier/c4#16]
It looks like if the first left hand side of a substract is int*, then it ignores the type of the right hand side and treats it like a number. The following program demonstrates it

    int main()
    {
      int *s, *e, v;
    
      s = (int*)0xbebebeb0;
      e = (int*)0xbebebeb4;
      v = e - s;
      if (v == 1)
        printf("passed\n");
      else
        printf("failed, e - s = %x\n", v);
      v = e - 1;
      if ((int)v == s)
        printf("passed\n");
      else
        printf("failed, e - s = %x\n", v);
    }

EarlGray's and my fork both hit this because we do "jitmap[pc - text]" where all jitmap, pc and text are of type int*. Maybe not really in EarlGray's fork because his c4x86.c cannot compile itself yet because he still relies on calling function pointer and not your qsort hack.

I think it's ok if c4 does not support this. But then it should warn something. Producing an incorrect program this way could be hard to track down.

**Comment by rswier** [comment]
Test is working now.
