### ISSUE TITLE
Does not compile for 64 bit. (segfault in line 442)

### ISSUE THREAD

**Issue by phiresky** [rswier/c4#2]
```
> uname -a
Linux 3.17.1-1-ARCH #1 SMP PREEMPT Wed Oct 15 15:04:35 CEST 2014 x86_64 GNU/Linux
> gcc -g -o c4 c4.c
[lots of warnings]
> ./c4 hello.c
segmentation fault (core dumped) ./c4 hello.c
```

 running in gdb

``````
Program received signal SIGSEGV, Segmentation fault.
0x000000000040392a in main (argc=1, argv=0x7fffffffe3b0) at c4.c:442
442   *--sp = EXIT; // call exit if main returns```
``````

Interestingly, running it with `valgrind ./c4 hello.c` works

**Comment by kleirbaby** [comment]
hello,when i compiled your code with -m32 option,the gcc gave me some errors,and like this:
In file included from /usr/include/stdio.h:27:0,
                 from c4.c:9:
/usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
compilation terminated.

my system is ubuntu 16.04 64 bit ,gcc-5.4.0

**Comment by nubok** [comment]
@kleirbaby 

Look whether https://www.quora.com/How-do-I-fix-fatal-error-sys-cdefs-h-file-not-found-include-sys-cdefs-h helps you.

**Comment by kleirbaby** [comment]
Thanks a lot.It's effective!
