### ISSUE TITLE
when I use "./c4 -s hello.c " ,display fault like that 

### ISSUE THREAD

**Issue by helinyu** [rswier/c4#25]
1: #include <stdio.h>
2: 
Segmentation fault: 11

**Comment by EarlGray** [comment]
Did you build it on a 64-bit machine without `-m32`? Please provide more details: what's your system, what compiler did you use?

**Comment by helinyu** [comment]
Thank you , I missed it .

**Comment by nubok** [comment]
Please close this bug.
